check if benchmark failed (#446)

diff --git a/.github/workflows/run-benchmark-v2.yml b/.github/workflows/run-benchmark-v2.yml
--- a/.github/workflows/run-benchmark-v2.yml
+++ b/.github/workflows/run-benchmark-v2.yml
@@ -77,6 +77,11 @@ jobs:
               break
             fi
 
+            if [ "$status" = "failed" ]; then
+              echo "Benchmark failed!"
+              exit 1
+            fi
+
             iteration=$((iteration + 1))
 
             if [ $iteration -lt $max_iterations ]; then
